version: '3.9'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: deathnoteuser
      POSTGRES_PASSWORD: deathnotepass
      POSTGRES_DB: deathnotedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=deathnoteuser
      - DB_PASSWORD=deathnotepass
      - DB_NAME=deathnotedb
    depends_on:
      - db

volumes:
  postgres_data:
